apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: bootcampapp
data:
  port: '80'
  host: '0.0.0.0'
  pgdatabase: 'k8s-postgres'
  pgport: '5432'
  hosturl: 'http://20.121.38.217' # External IP of ingress-nginx-controller
  oktaurl: 'https://dev-18290583.okta.com'
  pghost: 'k8s-postgres.postgres.database.azure.com'
