  apiVersion: v1
    kind: Secret
    metadata:
      name: app-secrets
      labels:
        app: bootcampapp
    data:
      pgusername: YWRtaW51c2VyQGs4cy1kYXRhYmFzZQ==
      pgpassword: YXZpc2hQYXNzdzByZCM=
      cookie_encrypt: c3VwZXJBd2Vzb21lUGFzc3dvcmRTdHJpbmdUaGF0SXNBdExlYXN0MzJDaGFyYWN0ZXJzTG9uZyE=
      oktaclient: MG9hNDNmMjExMDNROFBQeVM1ZDc=
      oktasecret: ZHM5bl9Ka1pVY2pZeEZwYjFjMl9rS09JSjhUVkFCOGhjdjk5Q2NPMg==
